using PyPlot

function plotcomparison()
	close("all")
	constP = readdlm("outputs/HeartRateConst100.csv")
	varryingP = readdlm("outputs/s01004-2531-07-20-08-50n.csv")

	alldata = Array[]
	push!(alldata, constP)
	push!(alldata, varryingP)
	@show size(alldata)
	colorcounter = 1.0
	numDataSets = length(alldata)+0.0
	figure(figsize=(30,20))
	PyPlot.hold(true)
	
	for x in alldata
		colorstr = string(1-colorcounter/(.001+numDataSets))
		@show colorstr
		t = x[:,1]
		FIIa_vein = x[:, 3]
		APC_heart = x[:, 12]
		APC_liver = x[:, 40]
		APC_bulk = x[:, 47]
		APC_artery = x[:, 26]
		TM_wound = x[:, 56]
		TRIGGER_liver = x[:, 43]
		FII_kidney = x[:, 30]
		volume_heart = x[:, 59]
		volume_lungs = x[:, 60]
		FII_heart = x[:, 9]
		volume_vein = x[:, 58]
		TM_lungs = x[:, 21]
		TRIGGER_heart = x[:, 15]
		PC_kidney = x[:, 32]
		ATIII_kidney = x[:, 34]
		APC_lungs = x[:, 19]
		PC_wound = x[:, 53]
		ATIII_artery = x[:, 27]
		TRIGGER_kidney = x[:, 36]
		PC_lungs = x[:, 18]
		volume_wound = x[:, 65]
		TRIGGER_bulk = x[:, 50]
		FIIa_bulk = x[:, 45]
		APC_vein = x[:, 5]
		FIIa_liver = x[:, 38]
		PC_bulk = x[:, 46]
		TM_heart = x[:, 14]
		FIIa_kidney = x[:, 31]
		FII_vein = x[:, 2]
		ATIII_bulk = x[:, 48]
		ATIII_wound = x[:, 55]
		APC_kidney = x[:, 33]
		FII_wound = x[:, 51]
		ATIII_liver = x[:, 41]
		TRIGGER_vein = x[:, 8]
		FIIa_heart = x[:, 10]
		FII_bulk = x[:, 44]
		volume_artery = x[:, 61]
		TM_kidney = x[:, 35]
		PC_vein = x[:, 4]
		volume_kidney = x[:, 62]
		PC_liver = x[:, 39]
		FII_liver = x[:, 37]
		TM_bulk = x[:, 49]
		ATIII_heart = x[:, 13]
		FIIa_lungs = x[:, 17]
		volume_liver = x[:, 63]
		TRIGGER_lungs = x[:, 22]
		PC_heart = x[:, 11]
		ATIII_lungs = x[:, 20]
		FIIa_wound = x[:, 52]
		FII_artery = x[:, 23]
		TM_vein = x[:, 7]
		PC_artery = x[:, 25]
		APC_wound = x[:, 54]
		TRIGGER_artery = x[:, 29]
		ATIII_vein = x[:, 6]
		FIIa_artery = x[:, 24]
		volume_bulk = x[:, 64]
		TM_artery = x[:, 28]
		TRIGGER_wound = x[:, 57]
		TM_liver = x[:, 42]
		FII_lungs = x[:, 16]

		
		 plt[:tight_layout]() 	 #to prevent plots from overlapping
		 plt[:subplot](8,7,1)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_wound ,linewidth=.5,color = colorstr)
		 title("FII_wound")
		 plt[:subplot](8,7,2)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_wound ,linewidth=.5,color = colorstr)
		 title("FIIa_wound")
		 plt[:subplot](8,7,3)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_wound ,linewidth=.5,color = colorstr)
		 title("PC_wound")
		 plt[:subplot](8,7,4)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_wound ,linewidth=.5,color = colorstr)
		 title("APC_wound")
		 plt[:subplot](8,7,5)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_wound ,linewidth=.5,color = colorstr)
		 title("ATIII_wound")
		 plt[:subplot](8,7,6)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_wound ,linewidth=.5,color = colorstr)
		 title("TM_wound")
		 plt[:subplot](8,7,7)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_wound ,linewidth=.5,color = colorstr)
		 title("TRIGGER_wound")
		 plt[:subplot](8,7,8)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_vein ,linewidth=.5,color = colorstr)
		 title("FII_vein")
		 plt[:subplot](8,7,9)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_vein ,linewidth=.5,color = colorstr)
		 title("FIIa_vein")
		 plt[:subplot](8,7,10)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_vein ,linewidth=.5,color = colorstr)
		 title("PC_vein")
		 plt[:subplot](8,7,11)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_vein ,linewidth=.5,color = colorstr)
		 title("APC_vein")
		 plt[:subplot](8,7,12)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_vein ,linewidth=.5,color = colorstr)
		 title("ATIII_vein")
		 plt[:subplot](8,7,13)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_vein ,linewidth=.5,color = colorstr)
		 title("TM_vein")
		 plt[:subplot](8,7,14)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_vein ,linewidth=.5,color = colorstr)
		 title("TRIGGER_vein")
		 plt[:subplot](8,7,15)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_artery ,linewidth=.5,color = colorstr)
		 title("FII_artery")
		 plt[:subplot](8,7,16)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_artery ,linewidth=.5,color = colorstr)
		 title("FIIa_artery")
		 plt[:subplot](8,7,17)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_artery ,linewidth=.5,color = colorstr)
		 title("PC_artery")
		 plt[:subplot](8,7,18)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_artery ,linewidth=.5,color = colorstr)
		 title("APC_artery")
		 plt[:subplot](8,7,19)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_artery ,linewidth=.5,color = colorstr)
		 title("ATIII_artery")
		 plt[:subplot](8,7,20)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_artery ,linewidth=.5,color = colorstr)
		 title("TM_artery")
		 plt[:subplot](8,7,21)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_artery ,linewidth=.5,color = colorstr)
		 title("TRIGGER_artery")
		 plt[:subplot](8,7,22)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_heart ,linewidth=.5,color = colorstr)
		 title("FII_heart")
		 plt[:subplot](8,7,23)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_heart ,linewidth=.5,color = colorstr)
		 title("FIIa_heart")
		 plt[:subplot](8,7,24)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_heart ,linewidth=.5,color = colorstr)
		 title("PC_heart")
		 plt[:subplot](8,7,25)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_heart ,linewidth=.5,color = colorstr)
		 title("APC_heart")
		 plt[:subplot](8,7,26)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_heart ,linewidth=.5,color = colorstr)
		 title("ATIII_heart")
		 plt[:subplot](8,7,27)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_heart ,linewidth=.5,color = colorstr)
		 title("TM_heart")
		 plt[:subplot](8,7,28)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_heart ,linewidth=.5,color = colorstr)
		 title("TRIGGER_heart")
		 plt[:subplot](8,7,29)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_kidney ,linewidth=.5,color = colorstr)
		 title("FII_kidney")
		 plt[:subplot](8,7,30)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_kidney ,linewidth=.5,color = colorstr)
		 title("FIIa_kidney")
		 plt[:subplot](8,7,31)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_kidney ,linewidth=.5,color = colorstr)
		 title("PC_kidney")
		 plt[:subplot](8,7,32)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_kidney ,linewidth=.5,color = colorstr)
		 title("APC_kidney")
		 plt[:subplot](8,7,33)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_kidney ,linewidth=.5,color = colorstr)
		 title("ATIII_kidney")
		 plt[:subplot](8,7,34)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_kidney ,linewidth=.5,color = colorstr)
		 title("TM_kidney")
		 plt[:subplot](8,7,35)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_kidney ,linewidth=.5,color = colorstr)
		 title("TRIGGER_kidney")
		 plt[:subplot](8,7,36)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_lungs ,linewidth=.5,color = colorstr)
		 title("FII_lungs")
		 plt[:subplot](8,7,37)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_lungs ,linewidth=.5,color = colorstr)
		 title("FIIa_lungs")
		 plt[:subplot](8,7,38)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_lungs ,linewidth=.5,color = colorstr)
		 title("PC_lungs")
		 plt[:subplot](8,7,39)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_lungs ,linewidth=.5,color = colorstr)
		 title("APC_lungs")
		 plt[:subplot](8,7,40)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_lungs ,linewidth=.5,color = colorstr)
		 title("ATIII_lungs")
		 plt[:subplot](8,7,41)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_lungs ,linewidth=.5,color = colorstr)
		 title("TM_lungs")
		 plt[:subplot](8,7,42)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_lungs ,linewidth=.5,color = colorstr)
		 title("TRIGGER_lungs")
		 plt[:subplot](8,7,43)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_liver ,linewidth=.5,color = colorstr)
		 title("FII_liver")
		 plt[:subplot](8,7,44)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_liver ,linewidth=.5,color = colorstr)
		 title("FIIa_liver")
		 plt[:subplot](8,7,45)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_liver ,linewidth=.5,color = colorstr)
		 title("PC_liver")
		 plt[:subplot](8,7,46)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_liver ,linewidth=.5,color = colorstr)
		 title("APC_liver")
		 plt[:subplot](8,7,47)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_liver ,linewidth=.5,color = colorstr)
		 title("ATIII_liver")
		 plt[:subplot](8,7,48)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_liver ,linewidth=.5,color = colorstr)
		 title("TM_liver")
		 plt[:subplot](8,7,49)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_liver ,linewidth=.5,color = colorstr)
		 title("TRIGGER_liver")
		 plt[:subplot](8,7,50)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FII_bulk ,linewidth=.5,color = colorstr)
		 title("FII_bulk")
		 plt[:subplot](8,7,51)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, FIIa_bulk ,linewidth=.5,color = colorstr)
		 title("FIIa_bulk")
		 plt[:subplot](8,7,52)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, PC_bulk ,linewidth=.5,color = colorstr)
		 title("PC_bulk")
		 plt[:subplot](8,7,53)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, APC_bulk ,linewidth=.5,color = colorstr)
		 title("APC_bulk")
		 plt[:subplot](8,7,54)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, ATIII_bulk ,linewidth=.5,color = colorstr)
		 title("ATIII_bulk")
		 plt[:subplot](8,7,55)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TM_bulk ,linewidth=.5,color = colorstr)
		 title("TM_bulk")
		 plt[:subplot](8,7,56)
		 plt[:tick_params](axis="both", which="major", labelsize=7)
		 plt[:tick_params](axis="both", which="minor", labelsize=7)
		 plt[:ticklabel_format](axis="y", useOffset=false)
		 plot(t, TRIGGER_bulk ,linewidth=.5,color = colorstr)
		 title("TRIGGER_bulk")

		colorcounter = 1.0+colorcounter;

	end
	savefig("ComparisonGreyConstHRBlackVarryingPPatients01004-2531-07-20-08-50n.png")
end

plotcomparison()
