#to process the text files generated by running sobol script

using DataFrames

function averageSobolOutput(datadir)
	filenames = readdir(datadir)
	colnames = Vector(["alpha", "alphaStDev", "N", "NStDev", "M", "MStDev", "k1", "k1StDev", "k2", "k2StDev", "tau1", "tau1StDev", "tau2", "tau2StDev", "tauAch", "tauAchStDev", "tauNor", "tauNorStDev", "beta", "betaStDev", "h0", "h0StDev", "mNor", "mNorStDev", "mAch", "mAchStDev"])
	#@show length(colnames)
	alldata = DataFrame(transpose(ones(length(colnames))))
	#@show head(alldata)
	rename!(alldata.colindex, [(symbol("x$i")=>symbol(colnames[i])) for i in collect(1:length(colnames))])
	for fn in filenames
		#@show fn
		if(contains(fn, "SobolResults"))
			data= readtable(string(datadir,fn), header = true,  separator = ' ',makefactors = true, nrows = 13, eltypes = [UTF8String, Float64, Float64, Float64, Float64])
			row = Float64[]
			for k in collect(1:size(data,1))
				#@show data[:S1][k]
				#abs to make all positive
				push!(row, abs(data[:S1][k]) )
				push!(row, abs(data[:ST][k]))
			end
			push!(alldata, transpose(row))
		end
	end
	deleterows!(alldata, 1) #remove filler row with ones
	return alldata
end

d=averageSobolOutput("/home/rachel/Documents/work/optimization/sensitivityanalysis/PCA/PCAProcessedOutputSept9/")
means = colwise(mean,d)
stds = colwise(std, d)
