# ----------------------------------------------------------------------------------- #
# Copyright (c) 2016 Varnerlab
# School of Chemical Engineering Purdue University
# W. Lafayette IN 46907 USA

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
include("SolveBalances.jl")
include("DataFile.jl")
using PyPlot
function runModel()
	 close("all") #close already open windows
	#set start time, stop time and step sizes
	 tstart=0
	 tend=45
	 step=0.02
	 data_dict = DataFile(tstart, tend, step)
	 t, x = SolveBalances(tstart, tend, step, data_dict)
	@show size(x)
	@show x[1]
	 #Alias the species vector
	Fibrin_monomer_artery = x[:, 68]
	volume_artery = x[:, 148]
	antiplasmin_bulk = x[:, 124]
	FIIa_vein = x[:, 2]
	PAI_1_kidney = x[:, 89]
	Plasminogen_vein = x[:, 11]
	PC_lungs = x[:, 39]
	Fibrinogen_lungs = x[:, 46]
	uPA_kidney = x[:, 85]
	Fibrin_wound = x[:, 134]
	Fibrinogen_wound = x[:, 136]
	TRIGGER_heart = x[:, 25]
	FII_artery = x[:, 55]
	TM_lungs = x[:, 42]
	Plasminogen_heart = x[:, 29]
	APC_artery = x[:, 58]
	tPA_artery = x[:, 66]
	ATIII_wound = x[:, 131]
	Fiber_wound = x[:, 144]
	ATIII_artery = x[:, 59]
	volume_bulk = x[:, 151]
	Fibrin_vein = x[:, 8]
	antiplasmin_wound = x[:, 142]
	volume_liver = x[:, 150]
	FIIa_kidney = x[:, 74]
	ATIII_liver = x[:, 95]
	uPA_wound = x[:, 139]
	PC_artery = x[:, 57]
	FIIa_heart = x[:, 20]
	Fiber_kidney = x[:, 90]
	PC_bulk = x[:, 111]
	Fibrin_monomer_vein = x[:, 14]
	uPA_heart = x[:, 31]
	TM_kidney = x[:, 78]
	APC_bulk = x[:, 112]
	antiplasmin_artery = x[:, 70]
	antiplasmin_liver = x[:, 106]
	Protofibril_heart = x[:, 33]
	Fiber_vein = x[:, 18]
	antiplasmin_lungs = x[:, 52]
	uPA_bulk = x[:, 121]
	Protofibril_artery = x[:, 69]
	TM_bulk = x[:, 114]
	FII_bulk = x[:, 109]
	TM_liver = x[:, 96]
	Fibrin_heart = x[:, 26]
	TRIGGER_wound = x[:, 133]
	PAI_1_heart = x[:, 35]
	Plasminogen_kidney = x[:, 83]
	PAI_1_bulk = x[:, 125]
	Plasmin_wound = x[:, 135]
	APC_wound = x[:, 130]
	volume_heart = x[:, 146]
	PAI_1_vein = x[:, 17]
	Fibrinogen_artery = x[:, 64]
	Plasminogen_artery = x[:, 65]
	uPA_lungs = x[:, 49]
	Fibrin_lungs = x[:, 44]
	tPA_kidney = x[:, 84]
	tPA_wound = x[:, 138]
	APC_vein = x[:, 4]
	FII_lungs = x[:, 37]
	volume_vein = x[:, 145]
	FIIa_bulk = x[:, 110]
	FII_wound = x[:, 127]
	Plasmin_lungs = x[:, 45]
	uPA_vein = x[:, 13]
	Fibrin_monomer_kidney = x[:, 86]
	uPA_artery = x[:, 67]
	Plasmin_liver = x[:, 99]
	PC_liver = x[:, 93]
	Plasmin_bulk = x[:, 117]
	Fiber_bulk = x[:, 126]
	APC_liver = x[:, 94]
	Plasminogen_wound = x[:, 137]
	Protofibril_wound = x[:, 141]
	Protofibril_liver = x[:, 105]
	tPA_heart = x[:, 30]
	FII_vein = x[:, 1]
	Plasminogen_lungs = x[:, 47]
	Fiber_lungs = x[:, 54]
	Fibrin_monomer_heart = x[:, 32]
	Fibrin_monomer_lungs = x[:, 50]
	ATIII_kidney = x[:, 77]
	APC_lungs = x[:, 40]
	Fibrin_kidney = x[:, 80]
	Plasminogen_liver = x[:, 101]
	TRIGGER_bulk = x[:, 115]
	Fibrinogen_kidney = x[:, 82]
	FII_liver = x[:, 91]
	TRIGGER_vein = x[:, 7]
	Plasmin_vein = x[:, 9]
	TRIGGER_lungs = x[:, 43]
	TM_artery = x[:, 60]
	antiplasmin_heart = x[:, 34]
	PC_kidney = x[:, 75]
	FIIa_wound = x[:, 128]
	Fibrin_monomer_liver = x[:, 104]
	TM_wound = x[:, 132]
	Protofibril_kidney = x[:, 87]
	volume_lungs = x[:, 147]
	uPA_liver = x[:, 103]
	PC_vein = x[:, 3]
	TRIGGER_artery = x[:, 61]
	TRIGGER_kidney = x[:, 79]
	FIIa_lungs = x[:, 38]
	Fibrinogen_bulk = x[:, 118]
	volume_wound = x[:, 152]
	PAI_1_artery = x[:, 71]
	tPA_bulk = x[:, 120]
	Fiber_heart = x[:, 36]
	tPA_lungs = x[:, 48]
	ATIII_bulk = x[:, 113]
	APC_kidney = x[:, 76]
	tPA_vein = x[:, 12]
	Fibrinogen_liver = x[:, 100]
	Plasmin_kidney = x[:, 81]
	Fibrin_liver = x[:, 98]
	Fibrin_monomer_bulk = x[:, 122]
	antiplasmin_vein = x[:, 16]
	Fibrin_artery = x[:, 62]
	PAI_1_liver = x[:, 107]
	Fibrin_monomer_wound = x[:, 140]
	PAI_1_wound = x[:, 143]
	PC_heart = x[:, 21]
	Fibrinogen_vein = x[:, 10]
	tPA_liver = x[:, 102]
	FII_heart = x[:, 19]
	Protofibril_lungs = x[:, 51]
	APC_heart = x[:, 22]
	TM_vein = x[:, 6]
	TM_heart = x[:, 24]
	FII_kidney = x[:, 73]
	antiplasmin_kidney = x[:, 88]
	FIIa_liver = x[:, 92]
	Plasminogen_bulk = x[:, 119]
	PC_wound = x[:, 129]
	PAI_1_lungs = x[:, 53]
	Fibrin_bulk = x[:, 116]
	Fiber_artery = x[:, 72]
	Fibrinogen_heart = x[:, 28]
	Protofibril_bulk = x[:, 123]
	volume_kidney = x[:, 149]
	ATIII_vein = x[:, 5]
	ATIII_heart = x[:, 23]
	Plasmin_artery = x[:, 63]
	Plasmin_heart = x[:, 27]
	FIIa_artery = x[:, 56]
	TRIGGER_liver = x[:, 97]
	Fiber_liver = x[:, 108]
	ATIII_lungs = x[:, 41]
	Protofibril_vein = x[:, 15]

	 #code to plot, using subplots
	 figure(figsize=(40,20))
	 PyPlot.hold(true)
	 plt[:tight_layout]() 	 #to prevent plots from overlapping
	 plt[:subplot](8,18,1)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_wound ,linewidth=2.0,"k")
	 title("FII_wound" ,fontsize=7)
	 plt[:subplot](8,18,2)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_wound ,linewidth=2.0,"k")
	 title("FIIa_wound" ,fontsize=7)
	 plt[:subplot](8,18,3)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_wound ,linewidth=2.0,"k")
	 title("PC_wound" ,fontsize=7)
	 plt[:subplot](8,18,4)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_wound ,linewidth=2.0,"k")
	 title("APC_wound" ,fontsize=7)
	 plt[:subplot](8,18,5)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_wound ,linewidth=2.0,"k")
	 title("ATIII_wound" ,fontsize=7)
	 plt[:subplot](8,18,6)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_wound ,linewidth=2.0,"k")
	 title("TM_wound" ,fontsize=7)
	 plt[:subplot](8,18,7)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_wound ,linewidth=2.0,"k")
	 title("TRIGGER_wound" ,fontsize=7)
	 plt[:subplot](8,18,8)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_wound ,linewidth=2.0,"k")
	 title("Fibrin_wound" ,fontsize=7)
	 plt[:subplot](8,18,9)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_wound ,linewidth=2.0,"k")
	 title("Plasmin_wound" ,fontsize=7)
	 plt[:subplot](8,18,10)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_wound ,linewidth=2.0,"k")
	 title("Fibrinogen_wound" ,fontsize=7)
	 plt[:subplot](8,18,11)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_wound ,linewidth=2.0,"k")
	 title("Plasminogen_wound" ,fontsize=7)
	 plt[:subplot](8,18,12)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_wound ,linewidth=2.0,"k")
	 title("tPA_wound" ,fontsize=7)
	 plt[:subplot](8,18,13)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_wound ,linewidth=2.0,"k")
	 title("uPA_wound" ,fontsize=7)
	 plt[:subplot](8,18,14)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_wound ,linewidth=2.0,"k")
	 title("Fibrin_monomer_wound" ,fontsize=7)
	 plt[:subplot](8,18,15)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_wound ,linewidth=2.0,"k")
	 title("Protofibril_wound" ,fontsize=7)
	 plt[:subplot](8,18,16)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_wound ,linewidth=2.0,"k")
	 title("antiplasmin_wound" ,fontsize=7)
	 plt[:subplot](8,18,17)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_wound ,linewidth=2.0,"k")
	 title("PAI_1_wound" ,fontsize=7)
	 plt[:subplot](8,18,18)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_wound ,linewidth=2.0,"k")
	 title("Fiber_wound" ,fontsize=7)
	 plt[:subplot](8,18,19)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_artery ,linewidth=2.0,"k")
	 title("FII_artery" ,fontsize=7)
	 plt[:subplot](8,18,20)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_artery ,linewidth=2.0,"k")
	 title("FIIa_artery" ,fontsize=7)
	 plt[:subplot](8,18,21)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_artery ,linewidth=2.0,"k")
	 title("PC_artery" ,fontsize=7)
	 plt[:subplot](8,18,22)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_artery ,linewidth=2.0,"k")
	 title("APC_artery" ,fontsize=7)
	 plt[:subplot](8,18,23)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_artery ,linewidth=2.0,"k")
	 title("ATIII_artery" ,fontsize=7)
	 plt[:subplot](8,18,24)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_artery ,linewidth=2.0,"k")
	 title("TM_artery" ,fontsize=7)
	 plt[:subplot](8,18,25)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_artery ,linewidth=2.0,"k")
	 title("TRIGGER_artery" ,fontsize=7)
	 plt[:subplot](8,18,26)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_artery ,linewidth=2.0,"k")
	 title("Fibrin_artery" ,fontsize=7)
	 plt[:subplot](8,18,27)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_artery ,linewidth=2.0,"k")
	 title("Plasmin_artery" ,fontsize=7)
	 plt[:subplot](8,18,28)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_artery ,linewidth=2.0,"k")
	 title("Fibrinogen_artery" ,fontsize=7)
	 plt[:subplot](8,18,29)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_artery ,linewidth=2.0,"k")
	 title("Plasminogen_artery" ,fontsize=7)
	 plt[:subplot](8,18,30)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_artery ,linewidth=2.0,"k")
	 title("tPA_artery" ,fontsize=7)
	 plt[:subplot](8,18,31)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_artery ,linewidth=2.0,"k")
	 title("uPA_artery" ,fontsize=7)
	 plt[:subplot](8,18,32)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_artery ,linewidth=2.0,"k")
	 title("Fibrin_monomer_artery" ,fontsize=7)
	 plt[:subplot](8,18,33)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_artery ,linewidth=2.0,"k")
	 title("Protofibril_artery" ,fontsize=7)
	 plt[:subplot](8,18,34)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_artery ,linewidth=2.0,"k")
	 title("antiplasmin_artery" ,fontsize=7)
	 plt[:subplot](8,18,35)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_artery ,linewidth=2.0,"k")
	 title("PAI_1_artery" ,fontsize=7)
	 plt[:subplot](8,18,36)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_artery ,linewidth=2.0,"k")
	 title("Fiber_artery" ,fontsize=7)
	 plt[:subplot](8,18,37)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_vein ,linewidth=2.0,"k")
	 title("FII_vein" ,fontsize=7)
	 plt[:subplot](8,18,38)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_vein ,linewidth=2.0,"k")
	 title("FIIa_vein" ,fontsize=7)
	 plt[:subplot](8,18,39)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_vein ,linewidth=2.0,"k")
	 title("PC_vein" ,fontsize=7)
	 plt[:subplot](8,18,40)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_vein ,linewidth=2.0,"k")
	 title("APC_vein" ,fontsize=7)
	 plt[:subplot](8,18,41)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_vein ,linewidth=2.0,"k")
	 title("ATIII_vein" ,fontsize=7)
	 plt[:subplot](8,18,42)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_vein ,linewidth=2.0,"k")
	 title("TM_vein" ,fontsize=7)
	 plt[:subplot](8,18,43)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_vein ,linewidth=2.0,"k")
	 title("TRIGGER_vein" ,fontsize=7)
	 plt[:subplot](8,18,44)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_vein ,linewidth=2.0,"k")
	 title("Fibrin_vein" ,fontsize=7)
	 plt[:subplot](8,18,45)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_vein ,linewidth=2.0,"k")
	 title("Plasmin_vein" ,fontsize=7)
	 plt[:subplot](8,18,46)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_vein ,linewidth=2.0,"k")
	 title("Fibrinogen_vein" ,fontsize=7)
	 plt[:subplot](8,18,47)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_vein ,linewidth=2.0,"k")
	 title("Plasminogen_vein" ,fontsize=7)
	 plt[:subplot](8,18,48)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_vein ,linewidth=2.0,"k")
	 title("tPA_vein" ,fontsize=7)
	 plt[:subplot](8,18,49)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_vein ,linewidth=2.0,"k")
	 title("uPA_vein" ,fontsize=7)
	 plt[:subplot](8,18,50)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_vein ,linewidth=2.0,"k")
	 title("Fibrin_monomer_vein" ,fontsize=7)
	 plt[:subplot](8,18,51)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_vein ,linewidth=2.0,"k")
	 title("Protofibril_vein" ,fontsize=7)
	 plt[:subplot](8,18,52)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_vein ,linewidth=2.0,"k")
	 title("antiplasmin_vein" ,fontsize=7)
	 plt[:subplot](8,18,53)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_vein ,linewidth=2.0,"k")
	 title("PAI_1_vein" ,fontsize=7)
	 plt[:subplot](8,18,54)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_vein ,linewidth=2.0,"k")
	 title("Fiber_vein" ,fontsize=7)
	 plt[:subplot](8,18,55)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_liver ,linewidth=2.0,"k")
	 title("FII_liver" ,fontsize=7)
	 plt[:subplot](8,18,56)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_liver ,linewidth=2.0,"k")
	 title("FIIa_liver" ,fontsize=7)
	 plt[:subplot](8,18,57)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_liver ,linewidth=2.0,"k")
	 title("PC_liver" ,fontsize=7)
	 plt[:subplot](8,18,58)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_liver ,linewidth=2.0,"k")
	 title("APC_liver" ,fontsize=7)
	 plt[:subplot](8,18,59)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_liver ,linewidth=2.0,"k")
	 title("ATIII_liver" ,fontsize=7)
	 plt[:subplot](8,18,60)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_liver ,linewidth=2.0,"k")
	 title("TM_liver" ,fontsize=7)
	 plt[:subplot](8,18,61)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_liver ,linewidth=2.0,"k")
	 title("TRIGGER_liver" ,fontsize=7)
	 plt[:subplot](8,18,62)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_liver ,linewidth=2.0,"k")
	 title("Fibrin_liver" ,fontsize=7)
	 plt[:subplot](8,18,63)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_liver ,linewidth=2.0,"k")
	 title("Plasmin_liver" ,fontsize=7)
	 plt[:subplot](8,18,64)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_liver ,linewidth=2.0,"k")
	 title("Fibrinogen_liver" ,fontsize=7)
	 plt[:subplot](8,18,65)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_liver ,linewidth=2.0,"k")
	 title("Plasminogen_liver" ,fontsize=7)
	 plt[:subplot](8,18,66)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_liver ,linewidth=2.0,"k")
	 title("tPA_liver" ,fontsize=7)
	 plt[:subplot](8,18,67)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_liver ,linewidth=2.0,"k")
	 title("uPA_liver" ,fontsize=7)
	 plt[:subplot](8,18,68)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_liver ,linewidth=2.0,"k")
	 title("Fibrin_monomer_liver" ,fontsize=7)
	 plt[:subplot](8,18,69)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_liver ,linewidth=2.0,"k")
	 title("Protofibril_liver" ,fontsize=7)
	 plt[:subplot](8,18,70)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_liver ,linewidth=2.0,"k")
	 title("antiplasmin_liver" ,fontsize=7)
	 plt[:subplot](8,18,71)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_liver ,linewidth=2.0,"k")
	 title("PAI_1_liver" ,fontsize=7)
	 plt[:subplot](8,18,72)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_liver ,linewidth=2.0,"k")
	 title("Fiber_liver" ,fontsize=7)
	 plt[:subplot](8,18,73)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_kidney ,linewidth=2.0,"k")
	 title("FII_kidney" ,fontsize=7)
	 plt[:subplot](8,18,74)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_kidney ,linewidth=2.0,"k")
	 title("FIIa_kidney" ,fontsize=7)
	 plt[:subplot](8,18,75)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_kidney ,linewidth=2.0,"k")
	 title("PC_kidney" ,fontsize=7)
	 plt[:subplot](8,18,76)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_kidney ,linewidth=2.0,"k")
	 title("APC_kidney" ,fontsize=7)
	 plt[:subplot](8,18,77)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_kidney ,linewidth=2.0,"k")
	 title("ATIII_kidney" ,fontsize=7)
	 plt[:subplot](8,18,78)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_kidney ,linewidth=2.0,"k")
	 title("TM_kidney" ,fontsize=7)
	 plt[:subplot](8,18,79)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_kidney ,linewidth=2.0,"k")
	 title("TRIGGER_kidney" ,fontsize=7)
	 plt[:subplot](8,18,80)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_kidney ,linewidth=2.0,"k")
	 title("Fibrin_kidney" ,fontsize=7)
	 plt[:subplot](8,18,81)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_kidney ,linewidth=2.0,"k")
	 title("Plasmin_kidney" ,fontsize=7)
	 plt[:subplot](8,18,82)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_kidney ,linewidth=2.0,"k")
	 title("Fibrinogen_kidney" ,fontsize=7)
	 plt[:subplot](8,18,83)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_kidney ,linewidth=2.0,"k")
	 title("Plasminogen_kidney" ,fontsize=7)
	 plt[:subplot](8,18,84)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_kidney ,linewidth=2.0,"k")
	 title("tPA_kidney" ,fontsize=7)
	 plt[:subplot](8,18,85)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_kidney ,linewidth=2.0,"k")
	 title("uPA_kidney" ,fontsize=7)
	 plt[:subplot](8,18,86)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_kidney ,linewidth=2.0,"k")
	 title("Fibrin_monomer_kidney" ,fontsize=7)
	 plt[:subplot](8,18,87)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_kidney ,linewidth=2.0,"k")
	 title("Protofibril_kidney" ,fontsize=7)
	 plt[:subplot](8,18,88)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_kidney ,linewidth=2.0,"k")
	 title("antiplasmin_kidney" ,fontsize=7)
	 plt[:subplot](8,18,89)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_kidney ,linewidth=2.0,"k")
	 title("PAI_1_kidney" ,fontsize=7)
	 plt[:subplot](8,18,90)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_kidney ,linewidth=2.0,"k")
	 title("Fiber_kidney" ,fontsize=7)
	 plt[:subplot](8,18,91)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_bulk ,linewidth=2.0,"k")
	 title("FII_bulk" ,fontsize=7)
	 plt[:subplot](8,18,92)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_bulk ,linewidth=2.0,"k")
	 title("FIIa_bulk" ,fontsize=7)
	 plt[:subplot](8,18,93)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_bulk ,linewidth=2.0,"k")
	 title("PC_bulk" ,fontsize=7)
	 plt[:subplot](8,18,94)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_bulk ,linewidth=2.0,"k")
	 title("APC_bulk" ,fontsize=7)
	 plt[:subplot](8,18,95)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_bulk ,linewidth=2.0,"k")
	 title("ATIII_bulk" ,fontsize=7)
	 plt[:subplot](8,18,96)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_bulk ,linewidth=2.0,"k")
	 title("TM_bulk" ,fontsize=7)
	 plt[:subplot](8,18,97)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_bulk ,linewidth=2.0,"k")
	 title("TRIGGER_bulk" ,fontsize=7)
	 plt[:subplot](8,18,98)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_bulk ,linewidth=2.0,"k")
	 title("Fibrin_bulk" ,fontsize=7)
	 plt[:subplot](8,18,99)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_bulk ,linewidth=2.0,"k")
	 title("Plasmin_bulk" ,fontsize=7)
	 plt[:subplot](8,18,100)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_bulk ,linewidth=2.0,"k")
	 title("Fibrinogen_bulk" ,fontsize=7)
	 plt[:subplot](8,18,101)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_bulk ,linewidth=2.0,"k")
	 title("Plasminogen_bulk" ,fontsize=7)
	 plt[:subplot](8,18,102)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_bulk ,linewidth=2.0,"k")
	 title("tPA_bulk" ,fontsize=7)
	 plt[:subplot](8,18,103)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_bulk ,linewidth=2.0,"k")
	 title("uPA_bulk" ,fontsize=7)
	 plt[:subplot](8,18,104)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_bulk ,linewidth=2.0,"k")
	 title("Fibrin_monomer_bulk" ,fontsize=7)
	 plt[:subplot](8,18,105)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_bulk ,linewidth=2.0,"k")
	 title("Protofibril_bulk" ,fontsize=7)
	 plt[:subplot](8,18,106)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_bulk ,linewidth=2.0,"k")
	 title("antiplasmin_bulk" ,fontsize=7)
	 plt[:subplot](8,18,107)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_bulk ,linewidth=2.0,"k")
	 title("PAI_1_bulk" ,fontsize=7)
	 plt[:subplot](8,18,108)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_bulk ,linewidth=2.0,"k")
	 title("Fiber_bulk" ,fontsize=7)
	 plt[:subplot](8,18,109)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_lungs ,linewidth=2.0,"k")
	 title("FII_lungs" ,fontsize=7)
	 plt[:subplot](8,18,110)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_lungs ,linewidth=2.0,"k")
	 title("FIIa_lungs" ,fontsize=7)
	 plt[:subplot](8,18,111)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_lungs ,linewidth=2.0,"k")
	 title("PC_lungs" ,fontsize=7)
	 plt[:subplot](8,18,112)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_lungs ,linewidth=2.0,"k")
	 title("APC_lungs" ,fontsize=7)
	 plt[:subplot](8,18,113)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_lungs ,linewidth=2.0,"k")
	 title("ATIII_lungs" ,fontsize=7)
	 plt[:subplot](8,18,114)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_lungs ,linewidth=2.0,"k")
	 title("TM_lungs" ,fontsize=7)
	 plt[:subplot](8,18,115)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_lungs ,linewidth=2.0,"k")
	 title("TRIGGER_lungs" ,fontsize=7)
	 plt[:subplot](8,18,116)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_lungs ,linewidth=2.0,"k")
	 title("Fibrin_lungs" ,fontsize=7)
	 plt[:subplot](8,18,117)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_lungs ,linewidth=2.0,"k")
	 title("Plasmin_lungs" ,fontsize=7)
	 plt[:subplot](8,18,118)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_lungs ,linewidth=2.0,"k")
	 title("Fibrinogen_lungs" ,fontsize=7)
	 plt[:subplot](8,18,119)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_lungs ,linewidth=2.0,"k")
	 title("Plasminogen_lungs" ,fontsize=7)
	 plt[:subplot](8,18,120)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_lungs ,linewidth=2.0,"k")
	 title("tPA_lungs" ,fontsize=7)
	 plt[:subplot](8,18,121)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_lungs ,linewidth=2.0,"k")
	 title("uPA_lungs" ,fontsize=7)
	 plt[:subplot](8,18,122)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_lungs ,linewidth=2.0,"k")
	 title("Fibrin_monomer_lungs" ,fontsize=7)
	 plt[:subplot](8,18,123)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_lungs ,linewidth=2.0,"k")
	 title("Protofibril_lungs" ,fontsize=7)
	 plt[:subplot](8,18,124)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_lungs ,linewidth=2.0,"k")
	 title("antiplasmin_lungs" ,fontsize=7)
	 plt[:subplot](8,18,125)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_lungs ,linewidth=2.0,"k")
	 title("PAI_1_lungs" ,fontsize=7)
	 plt[:subplot](8,18,126)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_lungs ,linewidth=2.0,"k")
	 title("Fiber_lungs" ,fontsize=7)
	 plt[:subplot](8,18,127)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_heart ,linewidth=2.0,"k")
	 title("FII_heart" ,fontsize=7)
	 plt[:subplot](8,18,128)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_heart ,linewidth=2.0,"k")
	 title("FIIa_heart" ,fontsize=7)
	 plt[:subplot](8,18,129)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_heart ,linewidth=2.0,"k")
	 title("PC_heart" ,fontsize=7)
	 plt[:subplot](8,18,130)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_heart ,linewidth=2.0,"k")
	 title("APC_heart" ,fontsize=7)
	 plt[:subplot](8,18,131)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_heart ,linewidth=2.0,"k")
	 title("ATIII_heart" ,fontsize=7)
	 plt[:subplot](8,18,132)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_heart ,linewidth=2.0,"k")
	 title("TM_heart" ,fontsize=7)
	 plt[:subplot](8,18,133)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_heart ,linewidth=2.0,"k")
	 title("TRIGGER_heart" ,fontsize=7)
	 plt[:subplot](8,18,134)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_heart ,linewidth=2.0,"k")
	 title("Fibrin_heart" ,fontsize=7)
	 plt[:subplot](8,18,135)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_heart ,linewidth=2.0,"k")
	 title("Plasmin_heart" ,fontsize=7)
	 plt[:subplot](8,18,136)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_heart ,linewidth=2.0,"k")
	 title("Fibrinogen_heart" ,fontsize=7)
	 plt[:subplot](8,18,137)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_heart ,linewidth=2.0,"k")
	 title("Plasminogen_heart" ,fontsize=7)
	 plt[:subplot](8,18,138)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_heart ,linewidth=2.0,"k")
	 title("tPA_heart" ,fontsize=7)
	 plt[:subplot](8,18,139)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_heart ,linewidth=2.0,"k")
	 title("uPA_heart" ,fontsize=7)
	 plt[:subplot](8,18,140)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_heart ,linewidth=2.0,"k")
	 title("Fibrin_monomer_heart" ,fontsize=7)
	 plt[:subplot](8,18,141)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_heart ,linewidth=2.0,"k")
	 title("Protofibril_heart" ,fontsize=7)
	 plt[:subplot](8,18,142)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_heart ,linewidth=2.0,"k")
	 title("antiplasmin_heart" ,fontsize=7)
	 plt[:subplot](8,18,143)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_heart ,linewidth=2.0,"k")
	 title("PAI_1_heart" ,fontsize=7)
	 plt[:subplot](8,18,144)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_heart ,linewidth=2.0,"k")
	 title("Fiber_heart" ,fontsize=7)
	savefig("output/AllSpeciesHorribleLayout45minStopBleedingSlowlyAt15.pdf")

	 #code to plot compartment volumes, using subplots
	 figure(figsize=(20,20))
	 PyPlot.hold(true)
	 plt[:tight_layout]() 	 #to prevent plots from overlapping
	 plt[:subplot](3.0,3.0,1)
	 plot(t, volume_vein)
	 title("volume_vein")
	 plt[:subplot](3.0,3.0,2)
	 plot(t, volume_heart)
	 title("volume_heart")
	 plt[:subplot](3.0,3.0,3)
	 plot(t, volume_lungs)
	 title("volume_lungs")
	 plt[:subplot](3.0,3.0,4)
	 plot(t, volume_artery)
	 title("volume_artery")
	 plt[:subplot](3.0,3.0,5)
	 plot(t, volume_kidney)
	 title("volume_kidney")
	 plt[:subplot](3.0,3.0,6)
	 plot(t, volume_liver)
	 title("volume_liver")
	 plt[:subplot](3.0,3.0,7)
	 plot(t, volume_bulk)
	 title("volume_bulk")
	 plt[:subplot](3.0,3.0,8)
	 plot(t, volume_wound)
	 title("volume_wound")
	 end
runModel()
