# ----------------------------------------------------------------------------------- #
# Copyright (c) 2016 Varnerlab
# School of Chemical Engineering Purdue University
# W. Lafayette IN 46907 USA

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
include("SolveBalances.jl")
include("DataFile.jl")
include("utilities.jl")
include("BalanceEquations.jl")
include("CoagulationModelFactory.jl")
using PyPlot
function runModel()
	 close("all") #close already open windows
	#set start time, stop time and step sizes
	 tstart=0
	 tend=60
	 step=0.02
	 allparams = readdlm("../../../../../rachel/Documents/fibrinolysis_model_w_platelets/parameterEstimation/Best2PerObjectiveParameters_25_05_2017OriginalShapeFunctionOnlyFittingtPA2.txt", '\t')
	currparams = allparams[4,:]
	problem_dict = buildCompleteDictFromOneVector(currparams)
	 data_dict = DataFile(tstart, tend, step)
	 t, x = SolveBalances(tstart, tend, step, data_dict,problem_dict)
	 #Alias the species vector
	PROTHOMBINASE_PLATELETS_vein=[a[11] for a in x]
	FIIa_bulk=[a[134] for a in x]
	APC_wound=[a[158] for a in x]
	TM_wound=[a[160] for a in x]
	TRIGGER_heart=[a[29] for a in x]
	PAI_1_liver=[a[131] for a in x]
	Protofibril_wound=[a[173] for a in x]
	Eps_artery=[a[74] for a in x]
	Fiber_wound=[a[176] for a in x]
	Plasmin_lungs=[a[57] for a in x]
	FV_FX_heart=[a[31] for a in x]
	APC_artery=[a[70] for a in x]
	PROTHOMBINASE_PLATELETS_heart=[a[33] for a in x]
	APC_liver=[a[114] for a in x]
	PROTHOMBINASE_PLATELETS_wound=[a[165] for a in x]
	Eps_kidney=[a[96] for a in x]
	FII_bulk=[a[133] for a in x]
	ATIII_lungs=[a[49] for a in x]
	Fibrin_monomer_artery=[a[84] for a in x]
	TRIGGER_liver=[a[117] for a in x]
	ATIII_kidney=[a[93] for a in x]
	TM_lungs=[a[50] for a in x]
	PROTHOMBINASE_PLATELETS_artery=[a[77] for a in x]
	Fibrinogen_artery=[a[80] for a in x]
	Fiber_liver=[a[132] for a in x]
	PC_wound=[a[157] for a in x]
	PAI_1_bulk=[a[153] for a in x]
	Plasmin_artery=[a[79] for a in x]
	ATIII_artery=[a[71] for a in x]
	FV_FXa_liver=[a[120] for a in x]
	Fiber_bulk=[a[154] for a in x]
	FV_FXa_artery=[a[76] for a in x]
	volume_wound=[a[184] for a in x]
	Plasmin_wound=[a[167] for a in x]
	Fibrin_liver=[a[122] for a in x]
	PROTHOMBINASE_PLATELETS_bulk=[a[143] for a in x]
	Fibrin_monomer_lungs=[a[62] for a in x]
	Protofibril_kidney=[a[107] for a in x]
	Plasminogen_wound=[a[169] for a in x]
	PAI_1_vein=[a[21] for a in x]
	FV_FXa_vein=[a[10] for a in x]
	Fibrinogen_kidney=[a[102] for a in x]
	volume_artery=[a[180] for a in x]
	Eps_wound=[a[162] for a in x]
	Protofibril_liver=[a[129] for a in x]
	Fiber_artery=[a[88] for a in x]
	uPA_bulk=[a[149] for a in x]
	ATIII_vein=[a[5] for a in x]
	Protofibril_lungs=[a[63] for a in x]
	Protofibril_heart=[a[41] for a in x]
	Plasminogen_vein=[a[15] for a in x]
	tPA_bulk=[a[148] for a in x]
	PROTHOMBINASE_PLATELETS_lungs=[a[55] for a in x]
	Fiber_lungs=[a[66] for a in x]
	FII_wound=[a[155] for a in x]
	Fibrin_monomer_bulk=[a[150] for a in x]
	TRIGGER_kidney=[a[95] for a in x]
	TRIGGER_bulk=[a[139] for a in x]
	FIIa_kidney=[a[90] for a in x]
	FII_liver=[a[111] for a in x]
	Fibrinogen_vein=[a[14] for a in x]
	PAI_1_wound=[a[175] for a in x]
	PC_bulk=[a[135] for a in x]
	Plasminogen_liver=[a[125] for a in x]
	Fibrin_monomer_wound=[a[172] for a in x]
	Fibrinogen_bulk=[a[146] for a in x]
	antiplasmin_liver=[a[130] for a in x]
	uPA_vein=[a[17] for a in x]
	PAI_1_lungs=[a[65] for a in x]
	Fiber_heart=[a[44] for a in x]
	Plasminogen_heart=[a[37] for a in x]
	Fiber_kidney=[a[110] for a in x]
	uPA_liver=[a[127] for a in x]
	Plasmin_vein=[a[13] for a in x]
	PROTHOMBINASE_PLATELETS_kidney=[a[99] for a in x]
	ATIII_bulk=[a[137] for a in x]
	FV_FX_bulk=[a[141] for a in x]
	uPA_kidney=[a[105] for a in x]
	Eps_heart=[a[30] for a in x]
	FII_vein=[a[1] for a in x]
	PC_lungs=[a[47] for a in x]
	PC_kidney=[a[91] for a in x]
	PAI_1_heart=[a[43] for a in x]
	FV_FX_vein=[a[9] for a in x]
	Fibrin_monomer_liver=[a[128] for a in x]
	Plasminogen_bulk=[a[147] for a in x]
	tPA_kidney=[a[104] for a in x]
	volume_bulk=[a[183] for a in x]
	Plasminogen_kidney=[a[103] for a in x]
	antiplasmin_bulk=[a[152] for a in x]
	tPA_heart=[a[38] for a in x]
	Eps_liver=[a[118] for a in x]
	APC_lungs=[a[48] for a in x]
	Fibrin_kidney=[a[100] for a in x]
	Plasminogen_artery=[a[81] for a in x]
	Eps_bulk=[a[140] for a in x]
	Protofibril_vein=[a[19] for a in x]
	TRIGGER_lungs=[a[51] for a in x]
	volume_vein=[a[177] for a in x]
	Plasmin_liver=[a[123] for a in x]
	FV_FX_wound=[a[163] for a in x]
	antiplasmin_kidney=[a[108] for a in x]
	FV_FXa_wound=[a[164] for a in x]
	FIIa_vein=[a[2] for a in x]
	FII_kidney=[a[89] for a in x]
	APC_bulk=[a[136] for a in x]
	Protofibril_bulk=[a[151] for a in x]
	Fibrin_bulk=[a[144] for a in x]
	FV_FXa_bulk=[a[142] for a in x]
	Fibrin_artery=[a[78] for a in x]
	ATIII_wound=[a[159] for a in x]
	FIIa_liver=[a[112] for a in x]
	Fibrin_monomer_kidney=[a[106] for a in x]
	PROTHOMBINASE_PLATELETS_liver=[a[121] for a in x]
	PAI_1_kidney=[a[109] for a in x]
	volume_liver=[a[182] for a in x]
	APC_heart=[a[26] for a in x]
	TM_bulk=[a[138] for a in x]
	APC_vein=[a[4] for a in x]
	Fibrinogen_wound=[a[168] for a in x]
	TM_kidney=[a[94] for a in x]
	ATIII_liver=[a[115] for a in x]
	FV_FXa_lungs=[a[54] for a in x]
	Fibrin_monomer_heart=[a[40] for a in x]
	Plasmin_kidney=[a[101] for a in x]
	uPA_wound=[a[171] for a in x]
	tPA_lungs=[a[60] for a in x]
	Fibrin_heart=[a[34] for a in x]
	volume_heart=[a[178] for a in x]
	PC_liver=[a[113] for a in x]
	Fibrin_vein=[a[12] for a in x]
	tPA_vein=[a[16] for a in x]
	APC_kidney=[a[92] for a in x]
	TM_artery=[a[72] for a in x]
	TM_heart=[a[28] for a in x]
	FV_FX_kidney=[a[97] for a in x]
	FIIa_artery=[a[68] for a in x]
	Fibrinogen_liver=[a[124] for a in x]
	uPA_heart=[a[39] for a in x]
	FIIa_lungs=[a[46] for a in x]
	Protofibril_artery=[a[85] for a in x]
	tPA_wound=[a[170] for a in x]
	PC_heart=[a[25] for a in x]
	antiplasmin_heart=[a[42] for a in x]
	volume_kidney=[a[181] for a in x]
	Fibrinogen_lungs=[a[58] for a in x]
	Plasminogen_lungs=[a[59] for a in x]
	Eps_vein=[a[8] for a in x]
	antiplasmin_vein=[a[20] for a in x]
	Eps_lungs=[a[52] for a in x]
	Fibrin_monomer_vein=[a[18] for a in x]
	PC_artery=[a[69] for a in x]
	Fibrin_wound=[a[166] for a in x]
	Plasmin_heart=[a[35] for a in x]
	uPA_artery=[a[83] for a in x]
	antiplasmin_lungs=[a[64] for a in x]
	Plasmin_bulk=[a[145] for a in x]
	FII_lungs=[a[45] for a in x]
	antiplasmin_artery=[a[86] for a in x]
	FII_artery=[a[67] for a in x]
	tPA_liver=[a[126] for a in x]
	FV_FXa_heart=[a[32] for a in x]
	tPA_artery=[a[82] for a in x]
	TRIGGER_vein=[a[7] for a in x]
	FV_FX_artery=[a[75] for a in x]
	PAI_1_artery=[a[87] for a in x]
	volume_lungs=[a[179] for a in x]
	PC_vein=[a[3] for a in x]
	uPA_lungs=[a[61] for a in x]
	Fibrinogen_heart=[a[36] for a in x]
	FV_FXa_kidney=[a[98] for a in x]
	antiplasmin_wound=[a[174] for a in x]
	TRIGGER_wound=[a[161] for a in x]
	Fiber_vein=[a[22] for a in x]
	TM_vein=[a[6] for a in x]
	FIIa_heart=[a[24] for a in x]
	TRIGGER_artery=[a[73] for a in x]
	FV_FX_liver=[a[119] for a in x]
	FIIa_wound=[a[156] for a in x]
	FV_FX_lungs=[a[53] for a in x]
	TM_liver=[a[116] for a in x]
	FII_heart=[a[23] for a in x]
	ATIII_heart=[a[27] for a in x]
	Fibrin_lungs=[a[56] for a in x]

	 #code to plot, using subplots
	 figure(figsize=(20,20))
	 PyPlot.hold(true)
	 plt[:tight_layout]() 	 #to prevent plots from overlapping
	 plt[:subplot](8,22,1)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_vein ,linewidth=2.0,"k")
	 title("FII_vein ",fontsize=7 )
	 plt[:subplot](8,22,2)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_vein ,linewidth=2.0,"k")
	 title("FIIa_vein ",fontsize=7 )
	 plt[:subplot](8,22,3)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_vein ,linewidth=2.0,"k")
	 title("PC_vein ",fontsize=7 )
	 plt[:subplot](8,22,4)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_vein ,linewidth=2.0,"k")
	 title("APC_vein ",fontsize=7 )
	 plt[:subplot](8,22,5)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_vein ,linewidth=2.0,"k")
	 title("ATIII_vein ",fontsize=7 )
	 plt[:subplot](8,22,6)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_vein ,linewidth=2.0,"k")
	 title("TM_vein ",fontsize=7 )
	 plt[:subplot](8,22,7)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_vein ,linewidth=2.0,"k")
	 title("TRIGGER_vein ",fontsize=7 )
	 plt[:subplot](8,22,8)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_vein ,linewidth=2.0,"k")
	 title("Eps_vein ",fontsize=7 )
	 plt[:subplot](8,22,9)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_vein ,linewidth=2.0,"k")
	 title("FV_FX_vein ",fontsize=7 )
	 plt[:subplot](8,22,10)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_vein ,linewidth=2.0,"k")
	 title("FV_FXa_vein ",fontsize=7 )
	 plt[:subplot](8,22,11)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_vein ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_vein ",fontsize=7 )
	 plt[:subplot](8,22,12)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_vein ,linewidth=2.0,"k")
	 title("Fibrin_vein ",fontsize=7 )
	 plt[:subplot](8,22,13)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_vein ,linewidth=2.0,"k")
	 title("Plasmin_vein ",fontsize=7 )
	 plt[:subplot](8,22,14)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_vein ,linewidth=2.0,"k")
	 title("Fibrinogen_vein ",fontsize=7 )
	 plt[:subplot](8,22,15)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_vein ,linewidth=2.0,"k")
	 title("Plasminogen_vein ",fontsize=7 )
	 plt[:subplot](8,22,16)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_vein ,linewidth=2.0,"k")
	 title("tPA_vein ",fontsize=7 )
	 plt[:subplot](8,22,17)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_vein ,linewidth=2.0,"k")
	 title("uPA_vein ",fontsize=7 )
	 plt[:subplot](8,22,18)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_vein ,linewidth=2.0,"k")
	 title("Fibrin_monomer_vein ",fontsize=7 )
	 plt[:subplot](8,22,19)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_vein ,linewidth=2.0,"k")
	 title("Protofibril_vein ",fontsize=7 )
	 plt[:subplot](8,22,20)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_vein ,linewidth=2.0,"k")
	 title("antiplasmin_vein ",fontsize=7 )
	 plt[:subplot](8,22,21)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_vein ,linewidth=2.0,"k")
	 title("PAI_1_vein ",fontsize=7 )
	 plt[:subplot](8,22,22)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_vein ,linewidth=2.0,"k")
	 title("Fiber_vein ",fontsize=7 )
	 plt[:subplot](8,22,23)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_heart ,linewidth=2.0,"k")
	 title("FII_heart ",fontsize=7 )
	 plt[:subplot](8,22,24)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_heart ,linewidth=2.0,"k")
	 title("FIIa_heart ",fontsize=7 )
	 plt[:subplot](8,22,25)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_heart ,linewidth=2.0,"k")
	 title("PC_heart ",fontsize=7 )
	 plt[:subplot](8,22,26)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_heart ,linewidth=2.0,"k")
	 title("APC_heart ",fontsize=7 )
	 plt[:subplot](8,22,27)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_heart ,linewidth=2.0,"k")
	 title("ATIII_heart ",fontsize=7 )
	 plt[:subplot](8,22,28)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_heart ,linewidth=2.0,"k")
	 title("TM_heart ",fontsize=7 )
	 plt[:subplot](8,22,29)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_heart ,linewidth=2.0,"k")
	 title("TRIGGER_heart ",fontsize=7 )
	 plt[:subplot](8,22,30)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_heart ,linewidth=2.0,"k")
	 title("Eps_heart ",fontsize=7 )
	 plt[:subplot](8,22,31)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_heart ,linewidth=2.0,"k")
	 title("FV_FX_heart ",fontsize=7 )
	 plt[:subplot](8,22,32)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_heart ,linewidth=2.0,"k")
	 title("FV_FXa_heart ",fontsize=7 )
	 plt[:subplot](8,22,33)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_heart ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_heart ",fontsize=7 )
	 plt[:subplot](8,22,34)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_heart ,linewidth=2.0,"k")
	 title("Fibrin_heart ",fontsize=7 )
	 plt[:subplot](8,22,35)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_heart ,linewidth=2.0,"k")
	 title("Plasmin_heart ",fontsize=7 )
	 plt[:subplot](8,22,36)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_heart ,linewidth=2.0,"k")
	 title("Fibrinogen_heart ",fontsize=7 )
	 plt[:subplot](8,22,37)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_heart ,linewidth=2.0,"k")
	 title("Plasminogen_heart ",fontsize=7 )
	 plt[:subplot](8,22,38)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_heart ,linewidth=2.0,"k")
	 title("tPA_heart ",fontsize=7 )
	 plt[:subplot](8,22,39)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_heart ,linewidth=2.0,"k")
	 title("uPA_heart ",fontsize=7 )
	 plt[:subplot](8,22,40)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_heart ,linewidth=2.0,"k")
	 title("Fibrin_monomer_heart ",fontsize=7 )
	 plt[:subplot](8,22,41)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_heart ,linewidth=2.0,"k")
	 title("Protofibril_heart ",fontsize=7 )
	 plt[:subplot](8,22,42)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_heart ,linewidth=2.0,"k")
	 title("antiplasmin_heart ",fontsize=7 )
	 plt[:subplot](8,22,43)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_heart ,linewidth=2.0,"k")
	 title("PAI_1_heart ",fontsize=7 )
	 plt[:subplot](8,22,44)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_heart ,linewidth=2.0,"k")
	 title("Fiber_heart ",fontsize=7 )
	 plt[:subplot](8,22,45)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_lungs ,linewidth=2.0,"k")
	 title("FII_lungs ",fontsize=7 )
	 plt[:subplot](8,22,46)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_lungs ,linewidth=2.0,"k")
	 title("FIIa_lungs ",fontsize=7 )
	 plt[:subplot](8,22,47)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_lungs ,linewidth=2.0,"k")
	 title("PC_lungs ",fontsize=7 )
	 plt[:subplot](8,22,48)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_lungs ,linewidth=2.0,"k")
	 title("APC_lungs ",fontsize=7 )
	 plt[:subplot](8,22,49)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_lungs ,linewidth=2.0,"k")
	 title("ATIII_lungs ",fontsize=7 )
	 plt[:subplot](8,22,50)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_lungs ,linewidth=2.0,"k")
	 title("TM_lungs ",fontsize=7 )
	 plt[:subplot](8,22,51)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_lungs ,linewidth=2.0,"k")
	 title("TRIGGER_lungs ",fontsize=7 )
	 plt[:subplot](8,22,52)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_lungs ,linewidth=2.0,"k")
	 title("Eps_lungs ",fontsize=7 )
	 plt[:subplot](8,22,53)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_lungs ,linewidth=2.0,"k")
	 title("FV_FX_lungs ",fontsize=7 )
	 plt[:subplot](8,22,54)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_lungs ,linewidth=2.0,"k")
	 title("FV_FXa_lungs ",fontsize=7 )
	 plt[:subplot](8,22,55)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_lungs ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_lungs ",fontsize=7 )
	 plt[:subplot](8,22,56)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_lungs ,linewidth=2.0,"k")
	 title("Fibrin_lungs ",fontsize=7 )
	 plt[:subplot](8,22,57)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_lungs ,linewidth=2.0,"k")
	 title("Plasmin_lungs ",fontsize=7 )
	 plt[:subplot](8,22,58)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_lungs ,linewidth=2.0,"k")
	 title("Fibrinogen_lungs ",fontsize=7 )
	 plt[:subplot](8,22,59)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_lungs ,linewidth=2.0,"k")
	 title("Plasminogen_lungs ",fontsize=7 )
	 plt[:subplot](8,22,60)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_lungs ,linewidth=2.0,"k")
	 title("tPA_lungs ",fontsize=7 )
	 plt[:subplot](8,22,61)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_lungs ,linewidth=2.0,"k")
	 title("uPA_lungs ",fontsize=7 )
	 plt[:subplot](8,22,62)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_lungs ,linewidth=2.0,"k")
	 title("Fibrin_monomer_lungs ",fontsize=7 )
	 plt[:subplot](8,22,63)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_lungs ,linewidth=2.0,"k")
	 title("Protofibril_lungs ",fontsize=7 )
	 plt[:subplot](8,22,64)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_lungs ,linewidth=2.0,"k")
	 title("antiplasmin_lungs ",fontsize=7 )
	 plt[:subplot](8,22,65)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_lungs ,linewidth=2.0,"k")
	 title("PAI_1_lungs ",fontsize=7 )
	 plt[:subplot](8,22,66)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_lungs ,linewidth=2.0,"k")
	 title("Fiber_lungs ",fontsize=7 )
	 plt[:subplot](8,22,67)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_artery ,linewidth=2.0,"k")
	 title("FII_artery ",fontsize=7 )
	 plt[:subplot](8,22,68)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_artery ,linewidth=2.0,"k")
	 title("FIIa_artery ",fontsize=7 )
	 plt[:subplot](8,22,69)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_artery ,linewidth=2.0,"k")
	 title("PC_artery ",fontsize=7 )
	 plt[:subplot](8,22,70)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_artery ,linewidth=2.0,"k")
	 title("APC_artery ",fontsize=7 )
	 plt[:subplot](8,22,71)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_artery ,linewidth=2.0,"k")
	 title("ATIII_artery ",fontsize=7 )
	 plt[:subplot](8,22,72)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_artery ,linewidth=2.0,"k")
	 title("TM_artery ",fontsize=7 )
	 plt[:subplot](8,22,73)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_artery ,linewidth=2.0,"k")
	 title("TRIGGER_artery ",fontsize=7 )
	 plt[:subplot](8,22,74)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_artery ,linewidth=2.0,"k")
	 title("Eps_artery ",fontsize=7 )
	 plt[:subplot](8,22,75)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_artery ,linewidth=2.0,"k")
	 title("FV_FX_artery ",fontsize=7 )
	 plt[:subplot](8,22,76)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_artery ,linewidth=2.0,"k")
	 title("FV_FXa_artery ",fontsize=7 )
	 plt[:subplot](8,22,77)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_artery ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_artery ",fontsize=7 )
	 plt[:subplot](8,22,78)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_artery ,linewidth=2.0,"k")
	 title("Fibrin_artery ",fontsize=7 )
	 plt[:subplot](8,22,79)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_artery ,linewidth=2.0,"k")
	 title("Plasmin_artery ",fontsize=7 )
	 plt[:subplot](8,22,80)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_artery ,linewidth=2.0,"k")
	 title("Fibrinogen_artery ",fontsize=7 )
	 plt[:subplot](8,22,81)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_artery ,linewidth=2.0,"k")
	 title("Plasminogen_artery ",fontsize=7 )
	 plt[:subplot](8,22,82)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_artery ,linewidth=2.0,"k")
	 title("tPA_artery ",fontsize=7 )
	 plt[:subplot](8,22,83)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_artery ,linewidth=2.0,"k")
	 title("uPA_artery ",fontsize=7 )
	 plt[:subplot](8,22,84)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_artery ,linewidth=2.0,"k")
	 title("Fibrin_monomer_artery ",fontsize=7 )
	 plt[:subplot](8,22,85)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_artery ,linewidth=2.0,"k")
	 title("Protofibril_artery ",fontsize=7 )
	 plt[:subplot](8,22,86)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_artery ,linewidth=2.0,"k")
	 title("antiplasmin_artery ",fontsize=7 )
	 plt[:subplot](8,22,87)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_artery ,linewidth=2.0,"k")
	 title("PAI_1_artery ",fontsize=7 )
	 plt[:subplot](8,22,88)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_artery ,linewidth=2.0,"k")
	 title("Fiber_artery ",fontsize=7 )
	 plt[:subplot](8,22,89)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_kidney ,linewidth=2.0,"k")
	 title("FII_kidney ",fontsize=7 )
	 plt[:subplot](8,22,90)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_kidney ,linewidth=2.0,"k")
	 title("FIIa_kidney ",fontsize=7 )
	 plt[:subplot](8,22,91)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_kidney ,linewidth=2.0,"k")
	 title("PC_kidney ",fontsize=7 )
	 plt[:subplot](8,22,92)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_kidney ,linewidth=2.0,"k")
	 title("APC_kidney ",fontsize=7 )
	 plt[:subplot](8,22,93)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_kidney ,linewidth=2.0,"k")
	 title("ATIII_kidney ",fontsize=7 )
	 plt[:subplot](8,22,94)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_kidney ,linewidth=2.0,"k")
	 title("TM_kidney ",fontsize=7 )
	 plt[:subplot](8,22,95)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_kidney ,linewidth=2.0,"k")
	 title("TRIGGER_kidney ",fontsize=7 )
	 plt[:subplot](8,22,96)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_kidney ,linewidth=2.0,"k")
	 title("Eps_kidney ",fontsize=7 )
	 plt[:subplot](8,22,97)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_kidney ,linewidth=2.0,"k")
	 title("FV_FX_kidney ",fontsize=7 )
	 plt[:subplot](8,22,98)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_kidney ,linewidth=2.0,"k")
	 title("FV_FXa_kidney ",fontsize=7 )
	 plt[:subplot](8,22,99)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_kidney ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_kidney ",fontsize=7 )
	 plt[:subplot](8,22,100)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_kidney ,linewidth=2.0,"k")
	 title("Fibrin_kidney ",fontsize=7 )
	 plt[:subplot](8,22,101)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_kidney ,linewidth=2.0,"k")
	 title("Plasmin_kidney ",fontsize=7 )
	 plt[:subplot](8,22,102)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_kidney ,linewidth=2.0,"k")
	 title("Fibrinogen_kidney ",fontsize=7 )
	 plt[:subplot](8,22,103)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_kidney ,linewidth=2.0,"k")
	 title("Plasminogen_kidney ",fontsize=7 )
	 plt[:subplot](8,22,104)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_kidney ,linewidth=2.0,"k")
	 title("tPA_kidney ",fontsize=7 )
	 plt[:subplot](8,22,105)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_kidney ,linewidth=2.0,"k")
	 title("uPA_kidney ",fontsize=7 )
	 plt[:subplot](8,22,106)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_kidney ,linewidth=2.0,"k")
	 title("Fibrin_monomer_kidney ",fontsize=7 )
	 plt[:subplot](8,22,107)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_kidney ,linewidth=2.0,"k")
	 title("Protofibril_kidney ",fontsize=7 )
	 plt[:subplot](8,22,108)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_kidney ,linewidth=2.0,"k")
	 title("antiplasmin_kidney ",fontsize=7 )
	 plt[:subplot](8,22,109)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_kidney ,linewidth=2.0,"k")
	 title("PAI_1_kidney ",fontsize=7 )
	 plt[:subplot](8,22,110)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_kidney ,linewidth=2.0,"k")
	 title("Fiber_kidney ",fontsize=7 )
	 plt[:subplot](8,22,111)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_liver ,linewidth=2.0,"k")
	 title("FII_liver ",fontsize=7 )
	 plt[:subplot](8,22,112)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_liver ,linewidth=2.0,"k")
	 title("FIIa_liver ",fontsize=7 )
	 plt[:subplot](8,22,113)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_liver ,linewidth=2.0,"k")
	 title("PC_liver ",fontsize=7 )
	 plt[:subplot](8,22,114)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_liver ,linewidth=2.0,"k")
	 title("APC_liver ",fontsize=7 )
	 plt[:subplot](8,22,115)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_liver ,linewidth=2.0,"k")
	 title("ATIII_liver ",fontsize=7 )
	 plt[:subplot](8,22,116)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_liver ,linewidth=2.0,"k")
	 title("TM_liver ",fontsize=7 )
	 plt[:subplot](8,22,117)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_liver ,linewidth=2.0,"k")
	 title("TRIGGER_liver ",fontsize=7 )
	 plt[:subplot](8,22,118)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_liver ,linewidth=2.0,"k")
	 title("Eps_liver ",fontsize=7 )
	 plt[:subplot](8,22,119)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_liver ,linewidth=2.0,"k")
	 title("FV_FX_liver ",fontsize=7 )
	 plt[:subplot](8,22,120)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_liver ,linewidth=2.0,"k")
	 title("FV_FXa_liver ",fontsize=7 )
	 plt[:subplot](8,22,121)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_liver ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_liver ",fontsize=7 )
	 plt[:subplot](8,22,122)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_liver ,linewidth=2.0,"k")
	 title("Fibrin_liver ",fontsize=7 )
	 plt[:subplot](8,22,123)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_liver ,linewidth=2.0,"k")
	 title("Plasmin_liver ",fontsize=7 )
	 plt[:subplot](8,22,124)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_liver ,linewidth=2.0,"k")
	 title("Fibrinogen_liver ",fontsize=7 )
	 plt[:subplot](8,22,125)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_liver ,linewidth=2.0,"k")
	 title("Plasminogen_liver ",fontsize=7 )
	 plt[:subplot](8,22,126)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_liver ,linewidth=2.0,"k")
	 title("tPA_liver ",fontsize=7 )
	 plt[:subplot](8,22,127)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_liver ,linewidth=2.0,"k")
	 title("uPA_liver ",fontsize=7 )
	 plt[:subplot](8,22,128)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_liver ,linewidth=2.0,"k")
	 title("Fibrin_monomer_liver ",fontsize=7 )
	 plt[:subplot](8,22,129)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_liver ,linewidth=2.0,"k")
	 title("Protofibril_liver ",fontsize=7 )
	 plt[:subplot](8,22,130)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_liver ,linewidth=2.0,"k")
	 title("antiplasmin_liver ",fontsize=7 )
	 plt[:subplot](8,22,131)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_liver ,linewidth=2.0,"k")
	 title("PAI_1_liver ",fontsize=7 )
	 plt[:subplot](8,22,132)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_liver ,linewidth=2.0,"k")
	 title("Fiber_liver ",fontsize=7 )
	 plt[:subplot](8,22,133)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_bulk ,linewidth=2.0,"k")
	 title("FII_bulk ",fontsize=7 )
	 plt[:subplot](8,22,134)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_bulk ,linewidth=2.0,"k")
	 title("FIIa_bulk ",fontsize=7 )
	 plt[:subplot](8,22,135)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_bulk ,linewidth=2.0,"k")
	 title("PC_bulk ",fontsize=7 )
	 plt[:subplot](8,22,136)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_bulk ,linewidth=2.0,"k")
	 title("APC_bulk ",fontsize=7 )
	 plt[:subplot](8,22,137)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_bulk ,linewidth=2.0,"k")
	 title("ATIII_bulk ",fontsize=7 )
	 plt[:subplot](8,22,138)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_bulk ,linewidth=2.0,"k")
	 title("TM_bulk ",fontsize=7 )
	 plt[:subplot](8,22,139)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_bulk ,linewidth=2.0,"k")
	 title("TRIGGER_bulk ",fontsize=7 )
	 plt[:subplot](8,22,140)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_bulk ,linewidth=2.0,"k")
	 title("Eps_bulk ",fontsize=7 )
	 plt[:subplot](8,22,141)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_bulk ,linewidth=2.0,"k")
	 title("FV_FX_bulk ",fontsize=7 )
	 plt[:subplot](8,22,142)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_bulk ,linewidth=2.0,"k")
	 title("FV_FXa_bulk ",fontsize=7 )
	 plt[:subplot](8,22,143)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_bulk ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_bulk ",fontsize=7 )
	 plt[:subplot](8,22,144)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_bulk ,linewidth=2.0,"k")
	 title("Fibrin_bulk ",fontsize=7 )
	 plt[:subplot](8,22,145)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_bulk ,linewidth=2.0,"k")
	 title("Plasmin_bulk ",fontsize=7 )
	 plt[:subplot](8,22,146)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_bulk ,linewidth=2.0,"k")
	 title("Fibrinogen_bulk ",fontsize=7 )
	 plt[:subplot](8,22,147)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_bulk ,linewidth=2.0,"k")
	 title("Plasminogen_bulk ",fontsize=7 )
	 plt[:subplot](8,22,148)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_bulk ,linewidth=2.0,"k")
	 title("tPA_bulk ",fontsize=7 )
	 plt[:subplot](8,22,149)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_bulk ,linewidth=2.0,"k")
	 title("uPA_bulk ",fontsize=7 )
	 plt[:subplot](8,22,150)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_bulk ,linewidth=2.0,"k")
	 title("Fibrin_monomer_bulk ",fontsize=7 )
	 plt[:subplot](8,22,151)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_bulk ,linewidth=2.0,"k")
	 title("Protofibril_bulk ",fontsize=7 )
	 plt[:subplot](8,22,152)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_bulk ,linewidth=2.0,"k")
	 title("antiplasmin_bulk ",fontsize=7 )
	 plt[:subplot](8,22,153)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_bulk ,linewidth=2.0,"k")
	 title("PAI_1_bulk ",fontsize=7 )
	 plt[:subplot](8,22,154)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_bulk ,linewidth=2.0,"k")
	 title("Fiber_bulk ",fontsize=7 )
	 plt[:subplot](8,22,155)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FII_wound ,linewidth=2.0,"k")
	 title("FII_wound ",fontsize=7 )
	 plt[:subplot](8,22,156)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FIIa_wound ,linewidth=2.0,"k")
	 title("FIIa_wound ",fontsize=7 )
	 plt[:subplot](8,22,157)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PC_wound ,linewidth=2.0,"k")
	 title("PC_wound ",fontsize=7 )
	 plt[:subplot](8,22,158)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, APC_wound ,linewidth=2.0,"k")
	 title("APC_wound ",fontsize=7 )
	 plt[:subplot](8,22,159)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, ATIII_wound ,linewidth=2.0,"k")
	 title("ATIII_wound ",fontsize=7 )
	 plt[:subplot](8,22,160)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TM_wound ,linewidth=2.0,"k")
	 title("TM_wound ",fontsize=7 )
	 plt[:subplot](8,22,161)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, TRIGGER_wound ,linewidth=2.0,"k")
	 title("TRIGGER_wound ",fontsize=7 )
	 plt[:subplot](8,22,162)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Eps_wound ,linewidth=2.0,"k")
	 title("Eps_wound ",fontsize=7 )
	 plt[:subplot](8,22,163)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FX_wound ,linewidth=2.0,"k")
	 title("FV_FX_wound ",fontsize=7 )
	 plt[:subplot](8,22,164)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, FV_FXa_wound ,linewidth=2.0,"k")
	 title("FV_FXa_wound ",fontsize=7 )
	 plt[:subplot](8,22,165)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PROTHOMBINASE_PLATELETS_wound ,linewidth=2.0,"k")
	 title("PROTHOMBINASE_PLATELETS_wound ",fontsize=7 )
	 plt[:subplot](8,22,166)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_wound ,linewidth=2.0,"k")
	 title("Fibrin_wound ",fontsize=7 )
	 plt[:subplot](8,22,167)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasmin_wound ,linewidth=2.0,"k")
	 title("Plasmin_wound ",fontsize=7 )
	 plt[:subplot](8,22,168)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrinogen_wound ,linewidth=2.0,"k")
	 title("Fibrinogen_wound ",fontsize=7 )
	 plt[:subplot](8,22,169)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Plasminogen_wound ,linewidth=2.0,"k")
	 title("Plasminogen_wound ",fontsize=7 )
	 plt[:subplot](8,22,170)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, tPA_wound ,linewidth=2.0,"k")
	 title("tPA_wound ",fontsize=7 )
	 plt[:subplot](8,22,171)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, uPA_wound ,linewidth=2.0,"k")
	 title("uPA_wound ",fontsize=7 )
	 plt[:subplot](8,22,172)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fibrin_monomer_wound ,linewidth=2.0,"k")
	 title("Fibrin_monomer_wound ",fontsize=7 )
	 plt[:subplot](8,22,173)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Protofibril_wound ,linewidth=2.0,"k")
	 title("Protofibril_wound ",fontsize=7 )
	 plt[:subplot](8,22,174)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, antiplasmin_wound ,linewidth=2.0,"k")
	 title("antiplasmin_wound ",fontsize=7 )
	 plt[:subplot](8,22,175)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, PAI_1_wound ,linewidth=2.0,"k")
	 title("PAI_1_wound ",fontsize=7 )
	 plt[:subplot](8,22,176)
	 plt[:tick_params](axis="both", which="major", labelsize=7)
	 plt[:tick_params](axis="both", which="minor", labelsize=7)
	 plt[:ticklabel_format](axis="y", useOffset=false)
	 plot(t, Fiber_wound ,linewidth=2.0,"k")
	 title("Fiber_wound ",fontsize=7 )
	 savefig("../figures/CompleteBody_21_08_17.pdf")

	 #code to plot compartment volumes, using subplots
	 figure(figsize=(20,20))
	 PyPlot.hold(true)
	 plt[:tight_layout]() 	 #to prevent plots from overlapping
	 plt[:subplot](3.0,3.0,1)
	 plot(t, volume_vein)
	 title("volume_vein")
	 plt[:subplot](3.0,3.0,2)
	 plot(t, volume_heart)
	 title("volume_heart")
	 plt[:subplot](3.0,3.0,3)
	 plot(t, volume_lungs)
	 title("volume_lungs")
	 plt[:subplot](3.0,3.0,4)
	 plot(t, volume_artery)
	 title("volume_artery")
	 plt[:subplot](3.0,3.0,5)
	 plot(t, volume_kidney)
	 title("volume_kidney")
	 plt[:subplot](3.0,3.0,6)
	 plot(t, volume_liver)
	 title("volume_liver")
	 plt[:subplot](3.0,3.0,7)
	 plot(t, volume_bulk)
	 title("volume_bulk")
	 plt[:subplot](3.0,3.0,8)
	 plot(t, volume_wound)
	 title("volume_wound")
	 return t,x
	 end

function runModel(paramNum,tend)
	 close("all") #close already open windows
	#set start time, stop time and step sizes
	 tstart=0
	# tend=60
	 step=0.02
	 allparams = readdlm("../../../../../rachel/Documents/fibrinolysis_model_w_platelets/parameterEstimation/Best2PerObjectiveParameters_25_05_2017OriginalShapeFunctionOnlyFittingtPA2.txt", '\t')
	currparams = allparams[paramNum,:]
	problem_dict = buildCompleteDictFromOneVector(currparams)
	 data_dict = DataFile(tstart, tend, step)
	 t, x = SolveBalances(tstart, tend, step, data_dict,problem_dict)
	return t,x
end

function runModelAllParams()
	numSpecies = 22
	numCompartments = 8
	tend = 60
	numParamSets=8
	allData = zeros(numSpecies*numCompartments,size(collect(0:.02:tend),1),numParamSets)
	for j in collect(1:numParamSets)
		t,x = runModel(j,tend)
		for k in collect(1:numSpecies*numCompartments)
			@show j
			@show size(([a[k] for a in x]))
			@show size(allData[k,j,:])
			allData[k,:,j]=([a[k] for a in x])
		end
	end
	writedlm("alldata_21_08_17.txt",allData)
	return t,allData
end
#runModel()
